### ISSUE TITLE
感谢大佬，请问如何安装？

### ISSUE THREAD

**Issue by l412198735** [SiriusXT/Zotero-Scholar-Rank#1]

**Comment by SiriusXT** [comment]
![图片](https://user-images.githubusercontent.com/37627919/162565110-565482d8-157f-40e2-a8c2-93aa65ce05c0.png)
直接下载这个zip文件，然后在zotero的工具->插件>从文件安装就行，安装完重启zotero，选择条目，右键update ranks就行。
![图片](https://user-images.githubusercontent.com/37627919/162565170-99d57442-fb1d-4c71-abe9-66e01837f7a7.png)
