### ISSUE TITLE
老哥，计算机学会出了2022年新版，不考虑集成进去吗

### ISSUE THREAD

**Issue by cauchyguo** [SiriusXT/Zotero-Scholar-Rank#10]
[计算机学会ccf列表](https://www.ccf.org.cn/Academic_Evaluation/By_category/)

**Comment by cauchyguo** [comment]
[中国计算机学会推荐国际学术会议和期刊目录-2022.pdf](https://github.com/SiriusXT/Zotero-Scholar-Rank/files/11966180/-2022.pdf)

**Comment by SiriusXT** [comment]
完成更新
