### ISSUE TITLE
提供一份最新版的影响因子和分区表

### ISSUE THREAD

**Issue by airsimonhan** [SiriusXT/Zotero-Scholar-Rank#12]
自己整理了一份2023最新版的分区和影响因子明细，望更新
链接：https://pan.baidu.com/s/1hrzReFKwSdlLqEycvh18pw?pwd=z3zx 
提取码：z3zx

**Comment by SiriusXT** [comment]
最近正在写论文，打算寒假的时候更新

**Comment by SiriusXT** [comment]
完成更新
