### ISSUE TITLE
服务器挂了https://scholarrank.ssang.top:28087/

### ISSUE THREAD

**Issue by normanleiden** [SiriusXT/Zotero-Scholar-Rank#5]
服务器挂了，无法访问 https://scholarrank.ssang.top:28087/了

**Comment by SiriusXT** [comment]
感谢提醒，已修复

**Comment by SiriusXT** [comment]
感谢提醒，应该已经修复，请重试。

于 2022年9月5日 GMT+08:00 下午6:59:32, normanleiden ***@***.***> 写到:
